In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df=pd.read_csv("House_Price.csv")

In [6]:
df.head()

price  crime_rate  resid_area  air_qual  room_num   age  dist1  dist2  \
0   24.0     0.00632       32.31     0.538     6.575  65.2   4.35   3.81   
1   21.6     0.02731       37.07     0.469     6.421  78.9   4.99   4.70   
2   34.7     0.02729       37.07     0.469     7.185  61.1   5.03   4.86   
3   33.4     0.03237       32.18     0.458     6.998  45.8   6.21   5.93   
4   36.2     0.06905       32.18     0.458     7.147  54.2   6.16   5.86   

   dist3  dist4  teachers  poor_prop airport  n_hos_beds  n_hot_rooms  \
0   4.18   4.01      24.7       4.98     YES       5.480      11.1920   
1   5.12   5.06      22.2       9.14      NO       7.332      12.1728   
2   5.01   4.97      22.2       4.03      NO       7.394     101.1200   
3   6.16   5.96      21.3       2.94     YES       9.268      11.2672   
4   6.37   5.86      21.3       5.33      NO       8.824      11.2896   

  waterbody  rainfall bus_ter     parks  
0     River        23     YES  0.049347  
1      Lake        42     YES  0.046146  
2      None        38     YES  0.045764  
3      Lake        45     YES  0.047151  
4      Lake        55     YES  0.039474

In [7]:
df.columns

Index(['price', 'crime_rate', 'resid_area', 'air_qual', 'room_num', 'age',
       'dist1', 'dist2', 'dist3', 'dist4', 'teachers', 'poor_prop', 'airport',
       'n_hos_beds', 'n_hot_rooms', 'waterbody', 'rainfall', 'bus_ter',
       'parks'],
      dtype='object')

In [8]:
df.isna().sum()

price          0
crime_rate     0
resid_area     0
air_qual       0
room_num       0
age            0
dist1          0
dist2          0
dist3          0
dist4          0
teachers       0
poor_prop      0
airport        0
n_hos_beds     8
n_hot_rooms    0
waterbody      0
rainfall       0
bus_ter        0
parks          0
dtype: int64

In [9]:
df["n_hos_beds"].fillna(df["n_hos_beds"].mode()[0], inplace=True)

In [10]:
df.isna().sum()

price          0
crime_rate     0
resid_area     0
air_qual       0
room_num       0
age            0
dist1          0
dist2          0
dist3          0
dist4          0
teachers       0
poor_prop      0
airport        0
n_hos_beds     0
n_hot_rooms    0
waterbody      0
rainfall       0
bus_ter        0
parks          0
dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   price        506 non-null    float64
 1   crime_rate   506 non-null    float64
 2   resid_area   506 non-null    float64
 3   air_qual     506 non-null    float64
 4   room_num     506 non-null    float64
 5   age          506 non-null    float64
 6   dist1        506 non-null    float64
 7   dist2        506 non-null    float64
 8   dist3        506 non-null    float64
 9   dist4        506 non-null    float64
 10  teachers     506 non-null    float64
 11  poor_prop    506 non-null    float64
 12  airport      506 non-null    object 
 13  n_hos_beds   506 non-null    float64
 14  n_hot_rooms  506 non-null    float64
 15  waterbody    506 non-null    object 
 16  rainfall     506 non-null    int64  
 17  bus_ter      506 non-null    object 
 18  parks        506 non-null    float64
dtypes: float

In [29]:
x = df.iloc[:, np.r_[1:12,13:15,16:17,18:19]].values
y = df.iloc[:, 0].values
print(x[0])
print(y[0])


[6.3200000e-03 3.2310000e+01 5.3800000e-01 6.5750000e+00 6.5200000e+01
 4.3500000e+00 3.8100000e+00 4.1800000e+00 4.0100000e+00 2.4700000e+01
 4.9800000e+00 5.4800000e+00 1.1192000e+01 2.3000000e+01 4.9347306e-02]
24.0


In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

from sklearn.preprocessing import LabelEncoder
Labelencoder_x=LabelEncoder()

In [31]:
x_train[0]

array([3.5809000e-01, 3.6200000e+01, 5.0700000e-01, 6.9510000e+00,
       8.8500000e+01, 3.0300000e+00, 2.7200000e+00, 3.0300000e+00,
       2.6600000e+00, 2.2600000e+01, 9.7100000e+00, 8.7340000e+00,
       1.1213600e+01, 2.3000000e+01, 5.3540387e-02])

In [32]:
x_test[0]

array([6.7240000e-02, 3.3240000e+01, 4.6000000e-01, 6.3330000e+00,
       1.7200000e+01, 5.3600000e+00, 5.0800000e+00, 5.4500000e+00,
       4.9700000e+00, 2.3100000e+01, 7.3400000e+00, 5.5520000e+00,
       1.4180800e+01, 5.3000000e+01, 4.5171644e-02])

In [33]:
y_train[0]

26.7

In [34]:
y_test[0]

22.6

In [35]:
for i in  range(0,18):
    x_train[:,i]=Labelencoder_x.fit_transform(x_train[:,i])
x_train  

IndexError: index 15 is out of bounds for axis 1 with size 15

In [36]:
Labelencoder_y=LabelEncoder()
y_train=Labelencoder_y.fit_transform(y_train)
y_train

array([148, 109, 149, 121,  15, 111,  99, 145, 201,  67, 113,  97,  62,
       135,   8, 122,  13, 213, 166,  27,  87, 105,  96,  81, 183,  80,
        89, 182,  33,   4,  38,  69,   8, 190, 131,  36, 144,   3,  33,
       136, 196, 140, 132,  63, 179, 193,  19,   3, 120, 158,  45, 135,
        76, 117,  98,  52,  69,  38,   6,  77, 190, 173, 180, 114,  97,
       130, 140,  30, 160,  25,  72, 149,  99,  14,  70,  90, 162,  98,
        49,  18,  88, 119,  88, 137, 140, 136, 213,  44,  23, 169, 158,
        59, 205, 140, 112,  92, 113, 209, 121,  95, 204, 185,  39, 134,
       107, 135, 105, 129, 147, 141,  12,  87,  87,  11,  41, 146,  39,
       186,  60, 109,  70,  55, 102, 109,  30,  80, 128,  86,  30, 108,
       124, 161, 105, 129,  66, 112, 195,  81, 111, 123,  95,  69, 180,
       132, 193,  56, 175,  37,  74,  35,  22, 202,  79,  33, 140, 105,
        57, 187, 142, 139, 107, 126,  82,  17, 103, 151,  70,  37, 158,
        48,  84, 157,  33,  83,  20,  35, 116,  94,  77, 121,  9

In [37]:
for i in  range(0,7):
    x_test[:,i]=Labelencoder_x.fit_transform(x_test[:,i])
x_test[0]

array([1.8000000e+01, 6.0000000e+00, 1.6000000e+01, 6.0000000e+01,
       2.0000000e+00, 7.0000000e+01, 6.7000000e+01, 5.4500000e+00,
       4.9700000e+00, 2.3100000e+01, 7.3400000e+00, 5.5520000e+00,
       1.4180800e+01, 5.3000000e+01, 4.5171644e-02])

In [38]:
Labelencoder_y=LabelEncoder()
y_test=Labelencoder_y.fit_transform(y_test)
y_test

array([46, 75, 47,  2, 41, 33, 39, 25, 17, 24,  3, 22, 13,  5, 75, 63, 47,
       70, 65, 40, 54, 28, 37, 64, 29, 48, 31, 30, 71, 25, 12, 34, 38, 35,
       52, 19,  0, 75, 11,  7, 55, 34, 32,  9, 18, 43, 36, 20,  6, 60, 16,
       48, 56, 72, 16, 44, 21, 22, 14, 44, 24, 40, 69, 68, 35, 66, 15, 14,
       60, 46, 34, 42, 51, 67, 53,  1, 74, 57, 46, 23, 50, 21, 61, 73, 75,
       47, 42,  4, 50, 49, 26,  8, 45, 59, 27, 56,  9, 58, 10, 25, 62, 32],
      dtype=int64)

In [43]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [45]:
y_pred = reg.predict(x_test)
y_pred

array([207.43169621, 188.22067359, 196.78147847, 181.72307673,
       199.09439454, 192.38094929, 189.97307393, 197.32695674,
       190.25083544, 195.54012503, 183.90143703, 187.92113746,
       186.99961912, 178.18607951, 199.93028851, 214.2147849 ,
       192.00270377, 216.33759607, 206.21533302, 197.20455075,
       200.57634741, 193.177087  , 192.55401769, 204.02106351,
       196.92915346, 183.22212646, 190.80562871, 188.87600924,
       209.09350006, 192.5916271 , 187.76410554, 186.54865321,
       201.27652231, 203.14572046, 203.77260927, 185.54079551,
       181.01146739, 187.51237375, 189.03936748, 185.04977987,
       201.661847  , 196.72292324, 204.94941399, 184.94479742,
       208.08181847, 202.39250444, 196.50604647, 191.34821287,
       183.17937259, 196.57563273, 191.2103719 , 189.69663727,
       198.32735576, 207.74151411, 183.61347407, 198.27963804,
       199.57062142, 200.67240716, 186.75851548, 192.84750806,
       205.44279292, 194.38927728, 208.61682262, 204.10

In [46]:
from sklearn.metrics import r2_score
r2_score(y_pred,y_test)

-317.88858272676015